SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
BASE_EXTRA_LIVES = 2
KEY_COOLDOWN = 0.5

BUTTON_WIDTH =  240
BUTTON_HEIGHT = 60
BUTTON_SPACING = 100

MODIFIER_COLORS = {"Att speed" : '#FF8000', "Invincibility" : '#00FF00', "Multi shot" : '#FF00FF', "Piercing shot" : '#FFFF00'}
MODIFIER_TYPES = ["Att speed", "Invincibility", "Multi shot", "Piercing shot"]
MODIFIER_TIMER = {"Att speed" : 8, "Invincibility" : 4, "Multi shot" : 8, "Piercing shot" : 8}
MODIFIER_SPAWN_RATE = 8
AVAILABLE_MODIFIERS_LIMIT = 4


